#!/usr/bin/with-contenv sh

#set -x

_term() {
  echo "Caught SIGTERM"
  exit 0
}

trap _term SIGTERM

# give time for gdrive to mount
sleep 2

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"
RCLONE_RC_ADDR=${RCLONE_RC_ADDR:-127.0.0.1:5572}
LOCAL_DATA=${LOCAL_DATA:-/seedbox/local}

# Clean up mount options
MountCommands=$(echo ${MountCommands} | xargs echo -n)

echo -e "${PREFFIX} ${Green}starting unionfs-fuse mount $(date +%Y.%m.%d-%T)\n ${Yellow} /usr/bin/unionfs-fuse -o cow, allow_other,statfs_omit_ro ${LOCAL_DATA}=RO:${MountPoint%/*}/rclone=RO ${MountPoint} ${Color_Off}"

# wait for gdrive mount
while true
do
  if ! grep -qs "${MountPoint%/*}/rclone" /proc/mounts; then
    echo "**** waiting for gdrive mount ****"
    sleep 5
    continue
  else
    echo "**** gdrive mounted ****"
    break
  fi
done

# mount unionfs-fuse
exec s6-setuidgid abc \
  /usr/bin/unionfs \
    -o cow,allow_non_empty,allow_other,statfs_omit_ro \
    ${LOCAL_DATA}=RO:${MountPoint%/*}/rclone=RO \
    ${MountPoint}

while true
do
  : # hold (unionfs-fuse forks to background)
done
