#!/usr/bin/with-contenv sh

#set -x

_term() {
  echo "Caught SIGTERM"
  exit 0
}

trap _term SIGTERM

# give time for gdrive to mount properly
sleep 5

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"
RCLONE_RC_ADDR=${RCLONE_RC_ADDR:-127.0.0.1:5572}
LOCAL_DATA=${LOCAL_DATA:-/seedbox/local}

# Clean up mount options
MountCommands=$(echo ${MountCommands} | xargs echo -n)
RcloneMountPoint="${MountPoint%/*}/rclone"

# wait for gdrive mount
while true
do
  if ! ls -la "${RcloneMountPoint}/${PREFIX}" > /dev/null; then
    echo "**** waiting for gdrive mount ****"
    sleep 2
   else
    # gdrive mounted
    echo -e "${PREFFIX} ${Green}starting unionfs-fuse mount $(date +%Y.%m.%d-%T)\n ${Yellow} /usr/bin/unionfs-fuse -f -o allow_other,statfs_omit_ro,ro ${LOCAL_DATA}=RO:${MountPoint%/*}/rclone=RO ${MountPoint} ${Color_Off}"
    # refresh vfs cache
    /usr/bin/rclone rc \
      vfs/refresh recursive=true \
      _async=true > /dev/null
    break
  fi
done

# mount unionfs-fuse
exec s6-setuidgid abc \
  /usr/bin/unionfs -f \
  -o cow,allow_other,statfs_omit_ro \
    ${LOCAL_DATA}=RW:${MountPoint%/*}/rclone=RO \
    ${MountPoint}
