version: 2

updates:
  -
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/bazarr/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/gcloud_init/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/radarr/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/rclone/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/rclone_generate_keys/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/sonarr/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    directory: "/traktarr/"
    schedule:
      interval: "daily"
  # Catch-all the rest
  -
    package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
