inputs:
  ghcr_username:
    description: Github Container Registry username
    required: true
  ghcr_password:
    description: Github Container Registry token
    required: true
  image:
    description: Image name
    required: true
  dockerfile:
    description: Path to dockerfile
    default: inputs.context/Dockerfile
  context:
    description: Dockerfile context
    default: .
  latest_tag_branch:
    description: What branch should be labelled as the 'latest' tag?
    default: main

runs:
  using: composite
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - uses: bluwy/substitute-string-action@v1
      id: dockerfile
      with:
        _input-text: ${{ inputs.dockerfile }}
        "inputs.context": ${{ inputs.context }}

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_password }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ steps.dockerfile.outputs.result }}
        push: true
        tags: |
          ghcr.io/${{ inputs.image }}:${{ env.GITHUB_REF_SLUG_URL == inputs.latest_tag_branch && 'latest' || env.GITHUB_REF_SLUG_URL }}
          ghcr.io/${{ inputs.image }}:${{ env.GITHUB_SHA_SHORT }}
#       cache-from: "${{ inputs.image }}:${{ env.GITHUB_REF_SLUG_URL == inputs.latest_tag_branch && 'latest' || env.GITHUB_REF_SLUG_URL }}"
