inputs:
  ghcr_username:
    description: GHCR username
    default: ${{ github.repository_owner }}
  ghcr_password:
    description: GHCR token
    required: true
  dockerfile:
    description: Path to dockerfile
    default: inputs.context/Dockerfile
  context:
    description: Dockerfile context
    default: .
  image:
    description: Image name
    required: true
  latest_tag_branch:
    description: What branch should be labelled as the 'latest' tag?
    default: main

runs:
  using: composite
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

#    - name: Login to Github Packages
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ inputs.ghcr_username }}
#        password: ${{ inputs.ghcr_password }}

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ inputs.ghcr_password }}" | docker login ghcr.io -u ${{ inputs.ghcr_username }} --password-stdin

    - uses: bluwy/substitute-string-action@v1
      id: dockerfile
      with:
        _input-text: ${{ inputs.dockerfile }}
        "inputs.context": ${{ inputs.context }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ steps.dockerfile.outputs.result }}
        push: true
        tags: "${{ inputs.image }}:${{ env.GITHUB_REF_SLUG_URL == inputs.latest_tag_branch && 'latest' || env.GITHUB_REF_SLUG_URL }},${{ inputs.image }}:${{ env.GITHUB_SHA_SHORT }}"
#       cache-from: "${{ inputs.image }}:${{ env.GITHUB_REF_SLUG_URL == inputs.latest_tag_branch && 'latest' || env.GITHUB_REF_SLUG_URL }}"
