version: 1
update_configs:
  - package-ecosystem: "docker"
    directory: "/bazarr/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  - package-ecosystem: "docker"
    directory: "/gcloud_init/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  - package-ecosystem: "docker"
    directory: "/radarr/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  - package-ecosystem: "docker"
    directory: "/rclone/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  - package-ecosystem: "docker"
    directory: "/rclone_generate_keys/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  - package-ecosystem: "docker"
    directory: "/sonarr/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  - package-ecosystem: "docker"
    directory: "/traktarr/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"

  # Catch-all the rest
  - package-ecosystem: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "edifus"
