#!/usr/bin/with-contenv sh

#set -x

# get rclone mountpoint
RcloneMountPoint="${MountPoint%/*}/rclone"

# make sure unmounted
/usr/bin/fusermount -u -z ${RcloneMountPoint}
/usr/bin/umount ${RcloneMountPoint}
