#!/usr/bin/with-contenv sh

#set -x

_term() {
  echo "Caught SIGTERM"
  exit 0
}

trap _term SIGTERM

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"

# Clean up mount options
MountCommands=$(echo ${MountCommands} | xargs echo -n)

echo -e "${PREFFIX} ${Green}starting rclone mount $(date +%Y.%m.%d-%T)\n ${Yellow} /usr/bin/rclone mount $MountCommands $RemotePath $MountPoint ${Color_Off}"

RCLONE_RC_PORT=${RCLONE_RC_PORT:-5572}

/usr/bin/rclone mount --rc-addr=0.0.0.0:${RCLONE_RC_PORT} $MountCommands $RemotePath $MountPoint
#/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 127.0.0.1:${RCLONE_RC_PORT} _async=true
