#!/usr/bin/with-contenv sh

#set -x

_term() {
  echo "Caught SIGTERM"
  exit 0
}

trap _term SIGTERM

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"
RCLONE_RC_ADDR=${RCLONE_RC_ADDR:-127.0.0.1:5572}

# Clean up mount options
MountCommands=$(echo ${MountCommands} | xargs echo -n)

echo -e "${PREFFIX} ${Green}starting rclone mount $(date +%Y.%m.%d-%T)\n ${Yellow} /usr/bin/rclone mount $MountCommands $RemotePath $MountPoint ${Color_Off}"

exec s6-setuidgid abc \
  /usr/bin/rclone mount \
  $MountCommands \
  $RemotePath \
  $MountPoint
#/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr ${RCLONE_RC_ADDR} _async=true
