name: Build containers

on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cancel_redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group:
          - image: "edifus/gcloud_init"
            dockerfile: "gcloud_init/Dockerfile"

          - image: "edifus/radarr"
            dockerfile: "radarr/Dockerfile"

#          - image: "edifus/rclone"
#            dockerfile: "rclone/Dockerfile"

          - image: "edifus/rclone_generate_keys"
            dockerfile: "rclone_generate_keys/Dockerfile"

          - image: "edifus/sonarr"
            dockerfile: "sonarr/Dockerfile"

#          - image: "edifus/bazarr"
#            dockerfile: "bazarr/Dockerfile"

#          - image: "edifus/traktarr"
#            dockerfile: "traktarr/Dockerfile"

#          - image: "edifus/headphones"
#            dockerfile: "headphones.Dockerfile"

#          - image: "edifus/lazylibrarian"
#            dockerfile: "lazylibrarian.Dockerfile"

#          - image: "edifus/medusa"
#            dockerfile: "medusa.Dockerfile"

#          - image: "edifus/mylar"
#            dockerfile: "mylar.Dockerfile"

#          - image: "edifus/nzbhydra2"
#            dockerfile: "nzbhydra2.Dockerfile"

#          - image: "edifus/sabnzbd"
#            dockerfile: "sabnzbd.Dockerfile"

#          - image: "edifus/transmission"
#            dockerfile: "transmission.Dockerfile"

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Build ${{ matrix.group.image }}
        uses: ./.github/actions/build-and-push-container
        with:
          ghcr_username: ${{ github.repository_owner }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.group.image }}
          dockerfile: ${{ matrix.group.dockerfile }}
